changed: pnpm to yarn

diff --git a/.github/workflows/firebase-hosting-pull-request.yml b/.github/workflows/firebase-hosting-pull-request.yml
--- a/.github/workflows/firebase-hosting-pull-request.yml
+++ b/.github/workflows/firebase-hosting-pull-request.yml
@@ -21,10 +21,10 @@ jobs:
           version: 6.0.2
 
       - name: Install dependencies
-        run: pnpm install
+        run: yarn install
 
       - name: Build
-        run: pnpm build || echo "Build failed but continuing with the workflow"
+        run: yarn build || echo "Build failed but continuing with the workflow"
 
       - name: Upload build files
         uses: actions/upload-artifact@v2
